version: '3'

services:
  app_tienda:
    build: app_tienda
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://ejercicio_tienda:3307/app_tienda?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 
    restart: always
    depends_on:
      ejercicio_tienda:
          condition: service_healthy
  ejercicio_tienda:
    image: 
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: ejercicio_tienda
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10